language: java
install: true
jdk:
  - openjdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2  
addons:
  sonarcloud:
    organization: "cesto93"
    token: $SONAR_TOKEN
script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=$PROJECT_KEY
